### ISSUE TITLE
AttributeError: 'range' object has no attribute 'remove'

### ISSUE THREAD

**Issue by etvedte** [fg6/random_subreads#1]
I'm trying to adopt this script for comparisons of ecoli assemblies generated using various long read sequencing technologies. I ran the following, using python v.3.5.2:

python subrand.py -i ecoli.trimmedReads.fasta -c 296 -r 4.6 -p Ecoli.pbRS.raw.fastq 

I'm assuming output files are automatically named based on the name of the input file, but no output was produced. Here is stdout stderr 

cat subrand.o3497814
/local/projects-t3/RDBKO/sequencing/ecoli.trimmedReads.fasta

 Getting a 296 X subsample of reads from ecoli.pb.sqII.trimmedReads.fasta
   (Coverage calculated for a reference size of 4.6 Mb)

cat subrand.e3497814
Traceback (most recent call last):
  File "/local/projects-t3/RDBKO/scripts/random_subreads/subrand.py", line 337, in <module>
    main(sys.argv[1:])
  File "/local/projects-t3/RDBKO/scripts/random_subreads/subrand.py", line 316, in main
    ok=read(inputfile,faqtype,cov,refsize)
  File "/local/projects-t3/RDBKO/scripts/random_subreads/subrand.py", line 45, in read
    listord.remove(thisr)
AttributeError: 'range' object has no attribute 'remove'

Any idea how I can solve this problem? Thanks in advance.

**Comment by claumer** [comment]
I'm getting a similar error with my own data - I guess it's a python version thing? Would love to be able to use this script in my own environment - it looks really handy!

**Comment by fg6** [comment]
Added a fix, but cannot test it right now. Does it work for you?
